//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAndRepayAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public string UserId { get; set; }
        public Nullable<int> CVR { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }
        public string StreetName { get; set; }
        public string HouseNumber { get; set; }
        public string CityName { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string CompanyName { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
